### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by makeworld-the-better-one** [hyphacoop/ansible-common#14]
There is no LICENSE file, making the legal status of using this repository murky. `galaxy.yml` mentions `GPL-2.0-or-later`, but I think that's just copied over and not necessarily the LICENSE we want to use.

**Comment by makeworld-the-better-one** [comment]
@dasanchez @ASoTNetworks @YurkoWasHere @uditvira @benhylau

**Comment by YurkoWasHere** [comment]
Added MIT license

**Comment by makeworld-the-better-one** [comment]
@YurkoWasHere `galaxy.yml` should be updated too: https://github.com/hyphacoop/ansible-common/blob/359e6cd11e0fa6569369bfb9233d2ac2e83c6c0b/galaxy.yml#L27-L28
