### ISSUE TITLE
Add PANIC setup

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/ansible-common#16]
Would it be possible to add a panic role like this one?
https://github.com/hyphacoop/cosmos-ansible/tree/main/roles/configure-panic

From cosmos-ansible repo discussion:
https://docs.google.com/document/d/1-ce2yTHeMKP6Lc-2wYPrzidu9rmWxvUmfT2bfaYKZS0/edit?disco=AAAAc5khzmo

**Comment by makeworld-the-better-one** [comment]
To me, [PANIC](https://github.com/SimplyVC/panic) looks specific to monitoring Cosmos nodes. Why would it be added to ansible-common instead of staying in cosmos-ansible where Cosmos-specific development is happening?

**Comment by makeworld-the-better-one** [comment]
After discussion, configure-panic will stay in cosmos-ansible.
